#!/bin/ash
psql -U postgres --command 'CREATE ROLE '"$DEFAULT_DATABASE_USER_NAME"' WITH SUPERUSER CREATEDB CREATEROLE LOGIN ENCRYPTED PASSWORD '\'"$DEFAULT_DATABASE_USER_PASSWORD"\'';'
psql -U postgres --command 'CREATE DATABASE '"$DEFAULT_DATABASE_NAME"' WITH OWNER '"$DEFAULT_DATABASE_USER_NAME"';'
psql -U $DEFAULT_DATABASE_USER_NAME -d $DEFAULT_DATABASE_NAME --command 'CREATE EXTENSION postgis;'
psql -U $DEFAULT_DATABASE_USER_NAME -d $DEFAULT_DATABASE_NAME --command 'CREATE EXTENSION postgis_topology;'
psql -U $DEFAULT_DATABASE_USER_NAME -d $DEFAULT_DATABASE_NAME --command 'CREATE EXTENSION fuzzystrmatch;'
psql -U $DEFAULT_DATABASE_USER_NAME -d $DEFAULT_DATABASE_NAME --command 'CREATE EXTENSION postgis_tiger_geocoder;'
if test -f "/var/dumps_pgsql/dump.sql"; then
    psql -U $DEFAULT_DATABASE_USER_NAME $DEFAULT_DATABASE_NAME < /var/dumps_pgsql/dump.sql
fi
